"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  getReport,
  type FeedbackReport,
} from "@/lib/api";
import {
  CheckCircleIcon,
  LightbulbIcon,
  MessageSquareIcon,
  TargetIcon,
  ArrowRightIcon,
  ChevronRightIcon,
} from "lucide-react";
import { Shimmer } from "@/components/ai-elements/shimmer";

export default function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const router = useRouter();
  const [report, setReport] = useState<FeedbackReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const { id } = await params;
        const result = await getReport(id);
        setReport(result.report);
      } catch (err: any) {
        setError(err.message ?? "Failed to load report");
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, [params]);

  if (loading) {
    return (
      <main className="flex-1 flex items-center justify-center">
        <Shimmer>Generating your feedback report...</Shimmer>
      </main>
    );
  }

  if (error || !report) {
    return (
      <main className="flex-1 flex flex-col items-center justify-center gap-4 px-4">
        <p className="text-destructive">{error || "Report not found"}</p>
        <Button onClick={() => router.push("/interview/create")}>
          Start New Interview
        </Button>
      </main>
    );
  }

  return (
    <main className="flex-1 px-4 py-12">
      <div className="mx-auto max-w-3xl space-y-10">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 shadow-lg">
            <CheckCircleIcon className="size-7 text-white" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight">
            Interview Report
          </h1>
          <p className="text-muted-foreground text-sm max-w-md mx-auto">
            Detailed feedback generated by the AI based on your full interview transcript.
          </p>
        </div>

        {/* Correctness */}
        <section className="rounded-xl border bg-card p-6 space-y-3">
          <div className="flex items-center gap-2">
            <TargetIcon className="size-5 text-blue-600" />
            <h2 className="font-semibold text-lg">Correctness &amp; Problem Solving</h2>
          </div>
          <p className="text-sm text-card-foreground leading-relaxed">
            {report.correctnessNotes}
          </p>
        </section>

        {/* Complexity Awareness */}
        <section className="rounded-xl border bg-card p-6 space-y-3">
          <div className="flex items-center gap-2">
            <LightbulbIcon className="size-5 text-amber-600" />
            <h2 className="font-semibold text-lg">Complexity &amp; Depth</h2>
          </div>
          <p className="text-sm text-card-foreground leading-relaxed">
            {report.complexityNotes}
          </p>
        </section>

        {/* Communication */}
        <section className="rounded-xl border bg-card p-6 space-y-3">
          <div className="flex items-center gap-2">
            <MessageSquareIcon className="size-5 text-violet-600" />
            <h2 className="font-semibold text-lg">Communication &amp; Clarity</h2>
          </div>
          <p className="text-sm text-card-foreground leading-relaxed">
            {report.communicationNotes}
          </p>
        </section>

        {/* Quoted Moments */}
        {report.quotedMoments?.length > 0 && (
          <section className="space-y-4">
            <h2 className="font-semibold text-lg flex items-center gap-2">
              <ChevronRightIcon className="size-5 text-muted-foreground" />
              Key Moments
            </h2>
            <div className="space-y-3">
              {report.quotedMoments.map((moment, i) => (
                <div
                  key={i}
                  className="rounded-xl border bg-card p-5 space-y-2"
                >
                  <div className="flex items-center gap-2">
                    <Badge
                      variant={moment.speaker === "user" ? "default" : "secondary"}
                      className="text-xs"
                    >
                      {moment.speaker === "user" ? "You" : "Interviewer"}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      Moment {i + 1}
                    </span>
                  </div>
                  <blockquote className="border-l-2 border-muted-foreground/30 pl-4 italic text-sm text-muted-foreground">
                    &ldquo;{moment.quote}&rdquo;
                  </blockquote>
                  <p className="text-sm text-card-foreground">{moment.why}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Next Steps */}
        <section className="rounded-xl border bg-card p-6 space-y-3">
          <div className="flex items-center gap-2">
            <ArrowRightIcon className="size-5 text-emerald-600" />
            <h2 className="font-semibold text-lg">Next Steps</h2>
          </div>
          <p className="text-sm text-card-foreground leading-relaxed">
            {report.nextSteps}
          </p>
        </section>

        {/* Actions */}
        <div className="flex justify-center gap-4 pt-4">
          <Button variant="outline" onClick={() => router.push("/interview/create")}>
            New Interview
          </Button>
          <Button onClick={() => router.push("/")}>
            Back to Home
          </Button>
        </div>
      </div>
    </main>
  );
}
